name: avito-shop-service

services:
  avito_shop_service:
    build: .
    container_name: avito_shop_service
    ports:
      - "${HTTP_PORT}:8080"
    depends_on:
      - avito_shop_migrate
    networks:
      - internal
  avito_shop_database:
    image: postgres:17
    env_file: .env
    container_name: avito_shop_database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DBNAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 2s
      timeout: 3s
      retries: 10
  avito_shop_migrate:
    image: migrate/migrate
    container_name: avito_shop_migrate
    depends_on:
      avito_shop_database:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DBNAME}?sslmode=disable",
        "up",
      ]
    networks:
      - internal
    restart: "on-failure:3"

volumes:
  pg_data:

networks:
  internal:
